In [3]:
import torch
print(torch.__version__)

1.13.0


In [4]:
 # Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [5]:
# Count number of devices
torch.cuda.device_count()

0

In [9]:
tensor = torch.tensor([1,2,3,4,5])
print(tensor,tensor.device)

tensor([1, 2, 3, 4, 5]) cpu


In [10]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4, 5])

# Exercises

In [20]:
#  Create a random tensor with shape (7, 7)
x = torch.rand(size=(7,7))
x

tensor([[0.4246, 0.1588, 0.4465, 0.1644, 0.1552, 0.3272, 0.7464],
        [0.6977, 0.9098, 0.7152, 0.7234, 0.9272, 0.9038, 0.0214],
        [0.4302, 0.6398, 0.3398, 0.8781, 0.0939, 0.5664, 0.3718],
        [0.5554, 0.9670, 0.7526, 0.9022, 0.2525, 0.3470, 0.7983],
        [0.2921, 0.4904, 0.2436, 0.7018, 0.9106, 0.0898, 0.6611],
        [0.6675, 0.9347, 0.2503, 0.5347, 0.0582, 0.5009, 0.3680],
        [0.8793, 0.5664, 0.3029, 0.8172, 0.8913, 0.4031, 0.5030]])

In [21]:
# Create another random tensor

# Perform matrix multiplication

# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

y = torch.rand(size=(1,7))

result = torch.matmul(x,y.T)

result

tensor([[1.2801],
        [2.0711],
        [1.5512],
        [2.3614],
        [1.4803],
        [1.8524],
        [2.0494]])

In [22]:
# Set manual seed


# Create two random tensors


# Matrix multiply tensors

torch.manual_seed(0)
x = torch.rand(size=(7,7))
y = torch.rand(size=(1,7))

result = torch.matmul(x,y.T)

result

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [23]:
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors 

torch.manual_seed(1234)
x = torch.rand(size=(2,3)).to(device)
y = torch.rand(size=(2,3)).to(device)
x, y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [24]:
z = torch.matmul(x,y.T)
z, z.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

In [25]:
# Find the maximum and minimum values of the output

maxx = torch.max(z)
minn = torch.min(z)

maxx, minn

(tensor(0.5617), tensor(0.3647))

In [26]:
#  Find the maximum and minimum index values of the output

maxx_idx = torch.argmax(z)
minn_idx = torch.argmax(z)

maxx_idx, minn_idx

(tensor(3), tensor(3))